---
- hosts: all
  connection: local
  gather_facts: false
  tasks: 
  - name: to gathering the facts
    ec2_instance_facts:
      region: us-east-2
    register: ec2_info
  - name: display the facts
    ec2:
      region: us-east-2
      instance_ids: "{{item.instance_id}}"
      state: absent
    with_items: "{{ec2_info.instances}}"
    when: item.tags.keys()|length == 0
